backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "work"
    label: "Projects"
    label_singular: "Project"
    files:
      - label: "Work Page"
        name: "work"
        file: "content/work.json"    
        fields:
          - label: "Projects"
            name: "projects"
            widget: list
            collapsed: true
            fields:
              - { label: "Title",       name: "title",     widget: "string" }
              - { label: "Description", name: "description",widget: "text"   }
              - { label: "Type",        name: "type",      widget: "string" }
              - { label: "Pages",       name: "pages",     widget: "string" }
              - { label: "Features",    name: "features",  widget: "string" }
              - { label: "Tech Stack",  name: "tech",      widget: "string" }
              - { label: "Timeline",    name: "timeline",  widget: "string" }
              - { label: "Live Link",   name: "link",      widget: "string" }
              - { label: "Case Study URL", name: "caseStudy",widget: "string" }
              - { label: "Test Field",   name: "test",      widget: "string" }

  - name: "team"
    label: "Team"
    extension: "json"
    format: "json"
    folder: "content"
    create: false
    identifier_field: "name"
    fields:
        - { label: "Name", name: "name", widget: "string" }
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Bio", name: "bio", widget: "text" }
        - {
              label: "Photos",
              name: "photos",
              widget: "list",
              field: { label: "Photo URL", name: "photo", widget: "image" }
            }     


              