backend:
  name: git-gateway
  branch: main
  site_url: "https://webwing.agency"
  identity_url: "https://webwing.agency/.netlify/identity"
  gateway_url: "https://webwing.agency/.netlify/git"

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "home"
    label: "Home"
    files:
      - name: "home"
        label: "Homepage"
        file: "content/index.json"
        format: "json"
        fields:
          - { name: "title", label: "Page Title", widget: "string" }
          - 
            name: "meta"
            label: "Meta"
            widget: "object"
            fields:
              - { name: "description", label: "Meta Description", widget: "text" }
          - 
            name: "hero"
            label: "Hero Section"
            widget: "object"
            fields:
              - { name: "heading", label: "Hero Heading", widget: "string" }
              - { name: "subheading", label: "Hero Subheading", widget: "text" }
              - { name: "backgroundVideo", label: "Background Video URL", widget: "file" }
              - { name: "ctaText", label: "Primary CTA Text", widget: "string" }
              - { name: "ctaLink", label: "Primary CTA Link", widget: "string" }
          - 
            name: "videoSection"
            label: "Videos"
            widget: "object"
            fields:
              - 
                name: "videos"
                label: "Video List"
                widget: "list"
                fields:
                  - { name: "title", label: "Video Title", widget: "string" }
                  - { name: "url", label: "Video File URL", widget: "file" }
                  - { name: "orientation", label: "Orientation (landscape/vertical)", widget: "string" }
          - 
            name: "offerSection"
            label: "What We Offer"
            widget: "object"
            fields:
              - { name: "sectionTitle", label: "Section Title", widget: "string" }
              - 
                name: "offers"
                label: "Offer Items"
                widget: "list"
                fields:
                  - { name: "icon", label: "Icon Path", widget: "image" }
                  - { name: "title", label: "Offer Title", widget: "string" }
                  - { name: "description", label: "Offer Description", widget: "text" }
          - 
            name: "projectsSection"
            label: "Projects"
            widget: "object"
            fields:
              - { name: "sectionTitle", label: "Section Title", widget: "string" }
              - 
                name: "projects"
                label: "Featured Projects"
                widget: "list"
                fields:
                  - { name: "title", label: "Project Title", widget: "string" }
                  - { name: "subtitle", label: "Subtitle", widget: "text" }
                  - { name: "url", label: "Live URL", widget: "string" }
                  - { name: "caseStudy", label: "Case Study URL", widget: "string" }
                  - { name: "screenshot", label: "Screenshot", widget: "image" }
                  - { name: "previewGif", label: "Preview GIF", widget: "file" }
          - 
            name: "ctaSection"
            label: "CTA"
            widget: "object"
            fields:
              - { name: "heading", label: "CTA Heading", widget: "string" }
              - { name: "subheading", label: "CTA Subheading", widget: "text" }
              - { name: "buttonText", label: "Button Text", widget: "string" }
              - { name: "buttonLink", label: "Button Link", widget: "string" }

  - name: "services"
    label: "Services"
    files:
      - label: "Services"
        name: "services"
        file: "content/services.json"   
        fields:
          - label: "Background Video"
            name: "bg_video"
            widget: "object"
            fields:

              - label: "Video File"
                name: "file"
                widget: "file"
                hint: "Upload or select an MP4 (or other supported video)."

              - label: "Poster Image (optional)"
                name: "poster"
                widget: "image"
                required: false
                hint: "This image will show before the video plays."
          - label: "Services"
            name: "services"
            widget: "list"
            summary: "{{fields.title}}"   
            fields:
              - { label: "Title",          name: "title",    widget: "string" }
              - { label: "Subtitle",       name: "subtitle", widget: "text" }

              - label: "Specifications (List)"
                name: "specs"
                widget: "list"
                summary: "{{fields.icon}}: {{fields.text}}"
                fields:
                  - { label: "Icon (Font-Awesome classes)", name: "icon", widget: "string", hint: "e.g. fas fa-headset" }
                  - { label: "Text",                 name: "text", widget: "string" }

  - name: "work"
    label: "Work"
    label_singular: "Project"
    files:
      - name: "work"
        label: "Work Page"
        file: "content/work.json"
        fields:
          - 
            label: "Projects"
            name: "projects"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Title",       name: "title",       widget: "string" }
              - { label: "Description", name: "description", widget: "text"   }
              - { label: "Type",        name: "type",        widget: "string" }
              - { label: "Pages",       name: "pages",       widget: "string" }
              - { label: "Features",    name: "features",    widget: "string" }
              - { label: "Tech Stack",  name: "tech",        widget: "string" }
              - { label: "Timeline",    name: "timeline",    widget: "string" }
              - { label: "Live Link",   name: "link",        widget: "string" }
              - { label: "Case Study URL", name: "caseStudy", widget: "string" }
              - { label: "Test Field",   name: "test",        widget: "string" }

  - name: "team"
    label: "Team"
    files:
      - name: "team"
        label: "Team Page"
        file: "content/team.json"
        format: "json"
        fields:
          - { label: "Page Title", name: "pageTitle",            widget: "string" }
          - { label: "Founder Section Title", name: "sectionTitle", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - 
            label: "Photos"
            name: "photos"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Name",  name: "name",  widget: "string" }
              - { label: "Role",  name: "role",  widget: "string" }


  - name: "impressum"
    label: "Impressum"
    file: "content/impressum.json"
    create: false
    slug: "index"
    editor:
      preview: false
    fields:
      - label: "Company Name"
        name: "company_name"
        widget: "string"
      - label: "Address (Street and Number)"
        name: "address_street"
        widget: "string"
      - label: "Postal Code"
        name: "postal_code"
        widget: "string"
      - label: "City"
        name: "city"
        widget: "string"
      - label: "Phone Number"
        name: "phone"
        widget: "string"
      - label: "Email Address"
        name: "email"
        widget: "string"
      - label: "Managing Director"
        name: "managing_director"
        widget: "string"
      - label: "Register Court"
        name: "register_court"
        widget: "string"
      - label: "Register Number"
        name: "register_number"
        widget: "string"
      - label: "VAT ID"
        name: "vat_id"
        widget: "string"
      - label: "Responsible Person (Name and Address)"
        name: "responsible_person"
        widget: "text"
